# Generated by Django 4.2.6 on 2023-10-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subplan_subplanfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplanfeature',
            name='subplan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subplan'),
        ),
    ]
