# Generated by Django 4.2.6 on 2023-10-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subplan_highlight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplan',
            name='highlight_status',
        ),
    ]
