# Generated by Django 4.2.6 on 2023-10-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_trainer_pwd_trainer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='pwd',
            new_name='password',
        ),
    ]
