# Generated by Django 4.2.6 on 2023-10-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_notifuserstatus_options_assignsubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignsubscriber',
            old_name='user',
            new_name='subscriber',
        ),
    ]
