# Generated by Django 4.2.6 on 2023-10-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_user_assignsubscriber_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignsubscriber',
            old_name='subscriber',
            new_name='user',
        ),
    ]
