# Generated by Django 4.2.6 on 2023-10-31 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_subscription_plan_alter_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='reg_date',
            new_name='register_date',
        ),
    ]
