# Generated by Django 4.2.6 on 2023-11-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_trainermsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermsg',
            name='user_type',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
