# Generated by Django 4.2.6 on 2023-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_trainermsg_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourOfferings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='ourOfferings/')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
