# Generated by Django 4.2.6 on 2023-11-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_ourofferings_delete_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourofferings',
            options={'verbose_name_plural': 'Banners'},
        ),
    ]
