# Generated by Django 4.2.6 on 2023-11-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_ourofferings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourofferings',
            options={'verbose_name_plural': 'ourOfferings'},
        ),
    ]
