# Generated by Django 4.2.6 on 2023-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_ourofferings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='slideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='slideShow/')),
                ('alt_text', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'slideShow',
            },
        ),
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
