# Generated by Django 4.2.6 on 2023-11-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_slideshow_delete_banners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshow',
            options={'verbose_name_plural': 'SlideShow'},
        ),
    ]
