# Generated by Django 4.2.6 on 2023-11-08 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_slideshow_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='event_images/')),
            ],
            options={
                'verbose_name_plural': 'EventImages',
            },
        ),
        migrations.CreateModel(
            name='FunEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='funEvents/')),
            ],
            options={
                'verbose_name_plural': 'FunEvents',
            },
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.AddField(
            model_name='eventimages',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.funevents'),
        ),
    ]
