# Generated by Django 4.2.6 on 2023-11-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_eventimages_funevents_remove_galleryimage_gallery_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='Queries',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='detail',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='full_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='send_time',
            new_name='time',
        ),
    ]
