# Generated by Django 4.2.6 on 2023-11-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_rename_enquiry_queries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queries',
            options={'verbose_name_plural': 'Queries'},
        ),
    ]
