# Generated by Django 4.2.6 on 2023-11-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_queries_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='f_name',
            new_name='Name',
        ),
    ]
