# Generated by Django 4.2.6 on 2023-11-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_faq_options_rename_ans_faq_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'MembershipFeatures',
            },
        ),
        migrations.CreateModel(
            name='MembershipPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('cost', models.IntegerField()),
                ('limit', models.IntegerField(null=True)),
                ('highlight', models.BooleanField(default=False, null=True)),
                ('validity', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Memberships',
            },
        ),
        migrations.DeleteModel(
            name='SubPlanFeature',
        ),
        migrations.AddField(
            model_name='membershipplanfeature',
            name='plan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.membershipplans'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.membershipplans'),
        ),
        migrations.DeleteModel(
            name='SubPlan',
        ),
    ]
