# Generated by Django 4.2.6 on 2023-11-09 04:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0049_membershipplanfeature_membershipplans_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Member',
        ),
    ]
