# Generated by Django 4.2.6 on 2023-11-09 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0050_rename_subscription_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('max_member', models.IntegerField(null=True)),
                ('highlight_status', models.BooleanField(default=False, null=True)),
                ('validity_days', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subplan', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subplan')),
            ],
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='quest',
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='Subscription',
        ),
        migrations.DeleteModel(
            name='MembershipPlanFeature',
        ),
        migrations.DeleteModel(
            name='MembershipPlans',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subplan'),
        ),
    ]
