# Generated by Django 4.2.6 on 2023-11-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_members_delete_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='member',
            new_name='user',
        ),
    ]
