# Generated by Django 4.2.6 on 2023-11-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_member_members_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='ans',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='quest',
            new_name='question',
        ),
    ]
