# Generated by Django 4.2.6 on 2023-11-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0054_alter_members_options_rename_ans_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notiftrainerstatus',
            options={'verbose_name_plural': 'TrainerNotificationStatus'},
        ),
        migrations.AlterModelOptions(
            name='trainermsg',
            options={'verbose_name_plural': 'TrainerMessages'},
        ),
        migrations.AlterModelOptions(
            name='trainernotification',
            options={'verbose_name_plural': 'TrainerNotification'},
        ),
        migrations.CreateModel(
            name='userTrainerUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateMsg', models.TextField()),
                ('updateFromTrainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updateFromTrainer', to='main.trainer')),
                ('updateFromUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updateFromUser', to=settings.AUTH_USER_MODEL)),
                ('updateToTrainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updateToTrainer', to='main.trainer')),
                ('updateToUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updateToUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
