# Generated by Django 4.2.6 on 2023-11-10 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0056_usermsg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notify',
            new_name='Notifications',
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'Notification'},
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='notify_detail',
            new_name='notification_detail',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='read_by_trainer',
            new_name='trainerRead',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='read_by_user',
            new_name='userRead',
        ),
    ]
